name: docker_build_push_acr

on:
  workflow_dispatch:

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.registry }}
        username: ${{ secrets.service_principal }}
        password: ${{ secrets.service_principal_password }}
        
    - name: 'Push to acr'
      run: |
        docker build src/product-service/ -t ${{ secrets.registry }}/product-service:${{ github.sha }}
        docker push ${{ secrets.registry }}/product-service:${{ github.sha }}
    # - name: Build the frontend image and push it to ACR
    #   uses: docker/build-push-action@v5
    #   with:
    #     push: true
    #     tags: '${{ secrets.registry }}/aspcoresample:${{ github.sha }}'
    #     file: src/product-service/Dockerfile
